services:
    dns-server:
        build: .
        container_name: dns-server-docker
        network_mode: host
        restart: unless-stopped
        volumes:
            - ./zones:/etc/bind/zones
            - ./named.conf:/etc/bind/named.conf
        command: named -g -c /etc/bind/named.conf
    
